[package]
name = "ash_shader_creator"
version = "1.0.0"
edition = "2018"
license = "MIT"
description = "A library for easy to way automatically create multiple shader stages from the directory path."
authors = ["Jerrody <huntermlg123465@gmail.com>"]

[dependencies]
ash = "0.33.0+1.2.186"